name: .NET Core CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    # Step 3: Install dependencies and restore
    - name: Restore dependencies
      run: dotnet restore MyApi/MyApi.csproj

    # Step 4: Build the project
    - name: Build the project
      run: dotnet build MyApi/MyApi.csproj --no-restore --configuration Release

    # Step 5: Run tests (if applicable)
    - name: Run tests
      run: dotnet test MyApi/MyApi.csproj --no-build --configuration Release

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    # Step 3: Deploy the project
    - name: Deploy application
      run: |
        echo "Deploying application..."
        # Add deployment steps here (e.g., copy files to a server, call deployment scripts)
        # Example placeholder:
        echo "Application deployed successfully!"
